[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = [
    "rm -f build/libs/*-plain.jar",
    "./gradlew clean bootJar -x test"
]

[start]
cmd = "java -jar $(find build/libs -maxdepth 1 -type f -name '*.jar' ! -name '*-plain.jar' | head -n 1)"