
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

oauth2:
  client-id: ${oauth2.client-id}
  team-id: ${oauth2.team-id}
  key-id: ${oauth2.key-id}
  private-key-path: ${oauth2.private-key-path}
  redirect-uri: ${oauth2.redirect-uri}
  authorize-uri: ${oauth2.authorize-uri}
  scope:
    - name
    - email

  web:
    resources:
      static-locations: file:uploads/images/ #file: 이 붙은 이유는 이 경로가 내 컴퓨터의 파일 경로임을 명시하기 위해서임
    cors:
      allowed-origins: http://localhost:3000



jwt:
  secret: ${jwt.secret}
  access-token-expiration: ${jwt.access-token-expiration}

apple:
  enabled : false