
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

oauth2:
  client-id: ${OAUTH2_CLIENT_ID}
  team-id: ${OAUTH2_TEAM_ID}
  key-id: ${OAUTH2_KEY_ID}
  private-key-path: ${OAUTH2_PRIVATE_KEY_PATH}
  redirect-uri: ${OAUTH2_REDIRECT_URI}
  authorize-uri: ${OAUTH2_AUTHORIZE_URI}
  scope:
    - name
    - email

  web:
    resources:
      static-locations: file:uploads/images/ #file: 이 붙은 이유는 이 경로가 내 컴퓨터의 파일 경로임을 명시하기 위해서임
    cors:
      allowed-origins: http://localhost:3000



jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

apple:
  enabled : true